export const theme = {
  colors: {
    primary: "#274864",
    secondary: "#16C0CB",
    text: "#4E4E4E",
    fund: "#E9FBF8",
    success: "#05B176",
    danger: "#FF0000",
    red: "#DF604F",
    grayYellow: "#E7E2C5",
    yellow: "#ECB83E",
    whitePrimary: "#FFFFFF",
    whiteSecondary: "#FDFDFF",
    gray: "#CDCACA",
    grayLight: "#EEEEEE",
  },
  fonts: {
    header: "4rem",
    h1: "4rem",
    h2: "3.5rem",
    h3: "3rem",
    h4: "1.75rem",
    h5: "1.25rem",
    h6: "0.75rem",
    txt: "1rem",
    txtBig: "1.1rem",
    txtsm: ".9rem",
  },
}
